{'gpu_num': '0', 'batch_size': 1024, 'n_epoch': 500, 'defalut_learning_rate': 0.001, 'fold_num': 5, 'scheduler_patience': 7, 'scheduler_factor': 0.7, 'erls_patience': 50, 'dataset': 'kincnn1', 'pretrain_fold_num': '0', 'model': 'KINCNN', 'save_dir': '/home/hb/python/efficientnet_kincnn/saved_model/0522/kincnn1_1804_bs1024_weight0'}
FOLD 0
--------------------------------
Traceback (most recent call last):
  File "/home/hb/python/efficientnet_kincnn/DeepPhospho.py", line 299, in <module>
    train_model_5cv()
  File "/home/hb/python/efficientnet_kincnn/DeepPhospho.py", line 115, in train_model_5cv
    scheduler = CosineAnnealingWarmupRestarts(optimizer, first_cycle_steps=50, cycle_mult=2, max_lr=0.1, min_lr=0.000001, warmup_starts=20, gamma=0.5)
TypeError: CosineAnnealingWarmupRestarts.__init__() got an unexpected keyword argument 'warmup_starts'